# Generated by Django 5.2.6 on 2025-10-04 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderTable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(blank=True, help_text='ID of the user making the payment, optional if not logged in', max_length=100, null=True)),
                ('user_name', models.CharField(help_text='Name of the person making the payment', max_length=255)),
                ('phone', models.CharField(help_text='Phone number of the person making the payment', max_length=15)),
                ('email', models.EmailField(blank=True, help_text='Email address of the person making the payment', max_length=255, null=True)),
                ('address', models.TextField(blank=True, help_text='Address of the person making the payment, optional', null=True)),
                ('gateway_order_id', models.CharField(blank=True, help_text='Order ID for the payment, can be used to track the payment', max_length=100, null=True)),
                ('gateway_payment_id', models.CharField(blank=True, help_text='Payment ID for the transaction, can be used to verify the payment', max_length=100, null=True)),
                ('ordered_products', models.JSONField(blank=True, help_text='Metadata related to the products being purchased, e.g., product IDs, names or descriptions', null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(default='INR', help_text='Currency of the payment, default is INR', max_length=10)),
                ('payment_gateway', models.CharField(help_text='Payment gateway used for the transaction', max_length=50)),
                ('payment_metadata', models.JSONField(blank=True, help_text='Metadata related to the payment, e.g., transaction ID, order ID', null=True)),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
