# Generated by Django 5.2.6 on 2025-10-08 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_course_user_year"),
        ("orders", "0002_ordertable"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ordertable",
            name="address",
        ),
        migrations.RemoveField(
            model_name="ordertable",
            name="email",
        ),
        migrations.RemoveField(
            model_name="ordertable",
            name="phone",
        ),
        migrations.RemoveField(
            model_name="ordertable",
            name="user_id",
        ),
        migrations.RemoveField(
            model_name="ordertable",
            name="user_name",
        ),
        migrations.AddField(
            model_name="ordertable",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.user",
            ),
            preserve_default=False,
        ),
    ]
