# Generated by Django 5.2.6 on 2025-10-04 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='icon',
            field=models.CharField(blank=True, help_text="Icon class name from 'react-icons'", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='coursetechnology',
            name='icon',
            field=models.CharField(blank=True, help_text='Icon class name from react icons', max_length=100, null=True),
        ),
    ]
