# Generated by Django 5.2.6 on 2025-10-05 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_alter_course_icon_alter_coursetechnology_icon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='price',
            new_name='discounted_price',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='crossed_price',
            new_name='original_price',
        ),
    ]
